language: cpp

compiler:
  - gcc
  - clang
  
script: 
  - mkdir build
  - cd build
  - cmake -DCMAKE_BUILD_TYPE=Debug -DCOVERALLS=true .
  - make
  - cp example/*.so .
  - make coveralls

after_sucess:
  - ./coveralls-upload

